"use client";

import { useEffect, useRef, useState } from "react";
import { WrenWarp } from "@/lib/wrenWarp";

// Wren — illustrated guide. A single illustration plus small overlay frames
// (mouth shapes + blink) generated by scripts/make-avatar-frames.py and scripts/make-blink-frames.py.
// Overlay positions are percentages of the 1254x1254 source image.

export type AvatarState = "idle" | "listening" | "thinking" | "talking";

const SRC = 1254;
const pct = (v: number) => `${(v / SRC) * 100}%`;
const MOUTH = { x: 618, y: 395, w: 132, h: 95 };
const EYES = { x: 560, y: 290, w: 215, h: 88 };
// Visible crop of the scene, centred on Wren (source pixels).
const CROP = { x: 250, y: 40, size: 800 };

const MOUTH_FRAMES = ["/avatar/m1.webp", "/avatar/m2.webp", "/avatar/m3.webp"];
const BLINK_FRAMES = ["/avatar/blink1.webp", "/avatar/blink2.webp"];

export default function Avatar({ state, mouthOpen }: { state: AvatarState; mouthOpen: number }) {
  // 0 = open, 1 = half-closed, 2 = closed
  const [blink, setBlink] = useState(0);

  // Natural blinking every 2.5–6 seconds: half → closed → half → open,
  // with an occasional double blink.
  useEffect(() => {
    const timers: ReturnType<typeof setTimeout>[] = [];
    const at = (ms: number, v: number) => timers.push(setTimeout(() => setBlink(v), ms));
    const blinkOnce = (start: number) => {
      at(start, 1);
      at(start + 55, 2);
      at(start + 150, 1);
      at(start + 205, 0);
    };
    let loop: ReturnType<typeof setTimeout>;
    const schedule = () => {
      loop = setTimeout(() => {
        blinkOnce(0);
        if (Math.random() < 0.2) blinkOnce(320);
        schedule();
      }, 2500 + Math.random() * 3500);
    };
    schedule();
    return () => {
      clearTimeout(loop);
      timers.forEach(clearTimeout);
    };
  }, []);

  const open = state === "talking" ? mouthOpen : 0;
  const mouthFrame = open < 0.2 ? null : open < 0.5 ? 0 : open < 0.8 ? 1 : 2;
  const scale = SRC / CROP.size;

  // Living-portrait layer: a WebGL warp drawn over the static picture once it's ready.
  // If WebGL isn't available, the static picture below stays.
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const warpRef = useRef<WrenWarp | null>(null);
  const [animated, setAnimated] = useState(false);
  useEffect(() => {
    if (!canvasRef.current) return;
    let warp: WrenWarp | null = null;
    try {
      warp = new WrenWarp(canvasRef.current, () => setAnimated(true));
      warpRef.current = warp;
      if (new URLSearchParams(window.location.search).has("wrenDebug")) {
        (window as unknown as { __wren?: WrenWarp }).__wren = warp;
      }
      warp.load().catch(() => setAnimated(false));
    } catch {
      setAnimated(false);
    }
    return () => {
      warp?.destroy();
      warpRef.current = null;
    };
  }, []);
  useEffect(() => {
    const w = warpRef.current;
    if (!w) return;
    w.state = state;
    w.mouthOpen = open;
    w.mouthFrame = mouthFrame;
    w.blink = blink;
    w.refresh();
  }, [state, open, mouthFrame, blink]);

  return (
    <div className={`avatar-wrap avatar-${state}`} aria-hidden="true">
      <div className="avatar-frame">
        <canvas ref={canvasRef} className="avatar-canvas" style={{ opacity: animated ? 1 : 0 }} />
        <div
          className={`avatar-scene${animated ? " avatar-scene-hidden" : ""}`}
          style={{
            width: `${scale * 100}%`,
            left: `${(-CROP.x / CROP.size) * 100}%`,
            top: `${(-CROP.y / CROP.size) * 100}%`,
          }}
        >
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img src="/avatar/wren-scene.webp" alt="" className="block w-full" draggable={false} />
          {MOUTH_FRAMES.map((src, i) => (
            // eslint-disable-next-line @next/next/no-img-element
            <img
              key={src}
              src={src}
              alt=""
              draggable={false}
              className="avatar-overlay"
              style={{
                left: pct(MOUTH.x),
                top: pct(MOUTH.y),
                width: pct(MOUTH.w),
                height: pct(MOUTH.h),
                opacity: mouthFrame === i ? 1 : 0,
              }}
            />
          ))}
          {BLINK_FRAMES.map((src, i) => (
            // eslint-disable-next-line @next/next/no-img-element
            <img
              key={src}
              src={src}
              alt=""
              draggable={false}
              className="avatar-overlay"
              style={{
                left: pct(EYES.x),
                top: pct(EYES.y),
                width: pct(EYES.w),
                height: pct(EYES.h),
                opacity: blink === i + 1 ? 1 : 0,
              }}
            />
          ))}
        </div>
      </div>
      {state === "thinking" && (
        <div className="avatar-dots">
          <span />
          <span />
          <span />
        </div>
      )}
    </div>
  );
}
