import Link from "next/link";
import LegalPage from "@/components/LegalPage";

export const metadata = { title: "Terms of use — Kindred Path" };

// DRAFT for attorney review. Bracketed items need the owner's details.
export default function TermsPage() {
  return (
    <LegalPage title="Terms of use" updated="October 3, 2026">
      <p>
        These terms apply to your use of Kindred Path, operated by [Company legal name] (&quot;we&quot;). By using the
        site you agree to them. If you don&apos;t agree, please don&apos;t use the site.
      </p>

      <h2>Kindred Path is not a law firm</h2>
      <ul>
        <li>We are not a law firm, and we don&apos;t provide legal, tax, financial, or medical advice.</li>
        <li>Wren is an AI guide, not a person and not a lawyer. Using Kindred Path does not create an attorney-client relationship with anyone.</li>
        <li>Everything here is general information. Laws, deadlines, and procedures differ by state and change over time, and your situation may have details that change the answer. Confirm decisions with a licensed professional in your state before you act.</li>
        <li>Wren does not draft wills, trusts, deeds, powers of attorney, court forms, or other legal documents.</li>
      </ul>

      <h2>AI can be wrong</h2>
      <p>
        Wren&apos;s replies and your summary are generated by artificial intelligence. They can be incomplete, out of
        date, or wrong. Please don&apos;t rely on them as the only basis for a decision.
      </p>

      <h2>If you are in crisis</h2>
      <p>
        Kindred Path is not an emergency or crisis service. If you are thinking about suicide or are in danger, call or
        text 988 (Suicide &amp; Crisis Lifeline, US) or call 911.
      </p>

      <h2>Listings and outside resources</h2>
      <p>
        The <Link href="/find" className="text-sage underline">Find a professional</Link> page shows search results
        from Google Maps, and other pages link to outside websites. We don&apos;t screen, endorse, rank, or get paid by
        any provider shown, and we aren&apos;t responsible for their services or websites. Please check any
        provider&apos;s license, fees, and reviews before hiring them.
      </p>

      <h2>Using the site responsibly</h2>
      <ul>
        <li>Don&apos;t share Social Security numbers, account numbers, or passwords.</li>
        <li>Don&apos;t try to misuse the AI, overload the site, get around its safety rules or bot protection, or use it to harm anyone.</li>
        <li>You must be at least 18 to use Kindred Path. [Attorney to confirm.]</li>
      </ul>

      <h2>No warranty and limits on liability</h2>
      <p>
        Kindred Path is provided &quot;as is&quot; and &quot;as available,&quot; without warranties of any kind, to the
        fullest extent the law allows. [Attorney to draft limitation of liability, indemnity, and dispute resolution
        terms appropriate to the business and the governing state.]
      </p>

      <h2>Governing law</h2>
      <p>These terms are governed by the laws of [State], without regard to conflict-of-law rules. [Attorney to confirm.]</p>

      <h2>Changes and contact</h2>
      <p>
        We may update these terms; the date at the top shows the latest version. Questions? Contact us at [contact
        email].
      </p>
    </LegalPage>
  );
}
